name: NFC Log

on:
  workflow_dispatch:
    inputs:
      uid:
        required: true
        type: string

jobs:
  append_log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run logging script
        run: python log_to_csv.py
        env:
          INPUT_UID: ${{ inputs.uid }}

      - name: Commit changes
        run: |
          git config user.name  "NFC Logger Bot"
          git config user.email "bot@example.com"
          git add nfc_log.csv
          git commit -m "Add log: ${{ inputs.uid }}" || echo "No changes"
          git push
